### PR TITLE
added .travis.yml file

### LINKED ISSUE #18: Setting up the Continuous Integration with Travis CI
At first, you have to take a subscription to Travis CI's official site by signing [here.](https://www.travis-ci.com/)

For your digest, read the complete [tutorial.](https://docs.travis-ci.com/user/tutorial/)

### I hope you enjoy it!

### PR DESCRIPTION
**Pull request by miguelangellus**
close #18

### CODE REVIEW

**Comment by miguelangellus** [comment]
Build Status:
[Build Status](https://app.travis-ci.com/miguelangellus/librarypython)

**Comment by miguelangellus** [comment]
Now it's okay, but it takes a long for updating the `Build Status` from the Trevis CI.

**Comment by marcosranes** [comment]
What happens is as your main branch was **behind the upstream**. You had to update your repository by **merging our main branches**. Now you can kill your PR's branch auxiliary sender 🚀🚀🚀

**Comment by miguelangellus** [comment]
I just had missed the auxiliary branch merging, and I received this **warning**, then I had to restore the branch here in Github and make the merging process.
```
miguelangellus@ubuntu21-vbox:~/Desktop/librarypython$ git checkout main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.

miguelangellus@ubuntu21-vbox:~/Desktop/librarypython$ git branch -d 18
warning: deleting branch '18' that has been merged to
         'refs/remotes/origin/18', but not yet merged to HEAD.
Deleted branch 18 (was 4d58dc9).

miguelangellus@ubuntu21-vbox:~/Desktop/librarypython$ git branch
* main

miguelangellus@ubuntu21-vbox:~/Desktop/librarypython$ ls -a
.   .flake8  .gitignore  libpython  README.md             requirements.txt
..  .git     .idea       LICENSE    requirements-dev.txt
miguelangellus@ubuntu21-vbox:~/Desktop/librarypython$ git fetch
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 4 (delta 1), reused 2 (delta 1), pack-reused 0
Unpacking objects: 100% (4/4), 972 bytes | 972.00 KiB/s, done.
From github.com:miguelangellus/librarypython
   4c6982e..8963de4  main       -> origin/main
miguelangellus@ubuntu21-vbox:~/Desktop/librarypython$ git pull
Updating 4c6982e..8963de4
Fast-forward
 .travis.yml | 7 +++++++
 1 file changed, 7 insertions(+)
 create mode 100644 .travis.yml

miguelangellus@ubuntu21-vbox:~/Desktop/librarypython$ ls -a
.   .flake8  .gitignore  libpython  README.md             requirements.txt
..  .git     .idea       LICENSE    requirements-dev.txt  .travis.yml
miguelangellus@ubuntu21-vbox:~/Desktop/librarypython$ 
```

**Comment by marcosranes** [comment]
You're welcome @miguelangellus 🎉🎉🎉

**Pull request merged**
